package atomicscience.muoxing;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

@SideOnly(Side.CLIENT)
public class MUnused extends ModelBase {
    ModelRenderer BASE;
    ModelRenderer SHIELD_1;
    ModelRenderer SHIELD_2;
    ModelRenderer SHIELD_3;
    ModelRenderer SHIELD_4;
    ModelRenderer REACTOR_SUPPORT_ROD_ROTATES;
    ModelRenderer SUPPORT_PLATE_1_ROTATES;
    ModelRenderer SUPPORT_PLATE_2_ROTATES;
    ModelRenderer FUEL_BAR_1_ROTATES;
    ModelRenderer FUEL_BAR_2_ROTATES;
    ModelRenderer FUEL_BAR_3_ROTATES;
    ModelRenderer FUEL_BAR_4_ROTATES;
    ModelRenderer CONVERTER;
    ModelRenderer SUB_SHIELD_1;
    ModelRenderer SUB_SHIELD_2;
    ModelRenderer Shape1;

    public MUnused() {
        super.textureWidth = 128;
        super.textureHeight = 128;
        this.BASE = new ModelRenderer(this, 0, 0);
        this.BASE.addBox(0.0F, 0.0F, 0.0F, 16, 1, 16);
        this.BASE.setRotationPoint(-8.0F, 23.0F, -8.0F);
        this.BASE.setTextureSize(128, 128);
        this.BASE.mirror = true;
        this.setRotation(this.BASE, 0.0F, 0.0F, 0.0F);
        this.SHIELD_1 = new ModelRenderer(this, 11, 18);
        this.SHIELD_1.addBox(0.0F, 0.0F, 0.0F, 1, 10, 8);
        this.SHIELD_1.setRotationPoint(0.0F, 13.0F, 6.0F);
        this.SHIELD_1.setTextureSize(128, 128);
        this.SHIELD_1.mirror = true;
        this.setRotation(this.SHIELD_1, 0.0F, -2.234021F, 0.0F);
        this.SHIELD_2 = new ModelRenderer(this, 0, 18);
        this.SHIELD_2.addBox(0.0F, 0.0F, 0.0F, 1, 10, 4);
        this.SHIELD_2.setRotationPoint(-7.0F, 13.0F, -2.0F);
        this.SHIELD_2.setTextureSize(128, 128);
        this.SHIELD_2.mirror = true;
        this.setRotation(this.SHIELD_2, 0.0F, 0.0F, 0.0F);
        this.SHIELD_3 = new ModelRenderer(this, 11, 37);
        this.SHIELD_3.addBox(0.0F, 0.0F, 0.0F, 1, 10, 8);
        this.SHIELD_3.setRotationPoint(5.0F, 13.0F, -3.0F);
        this.SHIELD_3.setTextureSize(128, 128);
        this.SHIELD_3.mirror = true;
        this.setRotation(this.SHIELD_3, 0.0F, 0.0F, 0.0F);
        this.SHIELD_4 = new ModelRenderer(this, 0, 37);
        this.SHIELD_4.addBox(0.0F, 0.0F, 0.0F, 1, 10, 4);
        this.SHIELD_4.setRotationPoint(6.0F, 13.0F, -3.0F);
        this.SHIELD_4.setTextureSize(128, 128);
        this.SHIELD_4.mirror = true;
        this.setRotation(this.SHIELD_4, 0.0F, -2.094395F, 0.0F);
        this.REACTOR_SUPPORT_ROD_ROTATES = new ModelRenderer(this, 0, 67);
        this.REACTOR_SUPPORT_ROD_ROTATES.addBox(-1.0F, 0.0F, -1.0F, 2, 13, 2);
        this.REACTOR_SUPPORT_ROD_ROTATES.setRotationPoint(0.0F, 10.0F, 0.0F);
        this.REACTOR_SUPPORT_ROD_ROTATES.setTextureSize(128, 128);
        this.REACTOR_SUPPORT_ROD_ROTATES.mirror = true;
        this.setRotation(this.REACTOR_SUPPORT_ROD_ROTATES, 0.0F, 0.0F, 0.0F);
        this.SUPPORT_PLATE_1_ROTATES = new ModelRenderer(this, 9, 57);
        this.SUPPORT_PLATE_1_ROTATES.addBox(-3.0F, 0.0F, -3.0F, 6, 1, 6);
        this.SUPPORT_PLATE_1_ROTATES.setRotationPoint(0.0F, 19.0F, 0.0F);
        this.SUPPORT_PLATE_1_ROTATES.setTextureSize(128, 128);
        this.SUPPORT_PLATE_1_ROTATES.mirror = true;
        this.setRotation(this.SUPPORT_PLATE_1_ROTATES, 0.0F, 0.7853982F, 0.0F);
        this.SUPPORT_PLATE_2_ROTATES = new ModelRenderer(this, 9, 57);
        this.SUPPORT_PLATE_2_ROTATES.addBox(-3.0F, 0.0F, -3.0F, 6, 1, 6);
        this.SUPPORT_PLATE_2_ROTATES.setRotationPoint(0.0F, 13.0F, 0.0F);
        this.SUPPORT_PLATE_2_ROTATES.setTextureSize(128, 128);
        this.SUPPORT_PLATE_2_ROTATES.mirror = true;
        this.setRotation(this.SUPPORT_PLATE_2_ROTATES, 0.0F, 0.7853982F, 0.0F);
        this.FUEL_BAR_1_ROTATES = new ModelRenderer(this, 0, 54);
        this.FUEL_BAR_1_ROTATES.addBox(-1.0F, 0.0F, 2.0F, 2, 9, 2);
        this.FUEL_BAR_1_ROTATES.setRotationPoint(0.0F, 12.0F, 0.0F);
        this.FUEL_BAR_1_ROTATES.setTextureSize(128, 128);
        this.FUEL_BAR_1_ROTATES.mirror = true;
        this.setRotation(this.FUEL_BAR_1_ROTATES, 0.0F, 0.0F, 0.0F);
        this.FUEL_BAR_2_ROTATES = new ModelRenderer(this, 0, 54);
        this.FUEL_BAR_2_ROTATES.addBox(2.0F, 0.0F, -1.0F, 2, 9, 2);
        this.FUEL_BAR_2_ROTATES.setRotationPoint(0.0F, 12.0F, 0.0F);
        this.FUEL_BAR_2_ROTATES.setTextureSize(128, 128);
        this.FUEL_BAR_2_ROTATES.mirror = true;
        this.setRotation(this.FUEL_BAR_2_ROTATES, 0.0F, 0.0F, 0.0F);
        this.FUEL_BAR_3_ROTATES = new ModelRenderer(this, 0, 54);
        this.FUEL_BAR_3_ROTATES.addBox(-1.0F, 0.0F, -4.0F, 2, 9, 2);
        this.FUEL_BAR_3_ROTATES.setRotationPoint(0.0F, 12.0F, 0.0F);
        this.FUEL_BAR_3_ROTATES.setTextureSize(128, 128);
        this.FUEL_BAR_3_ROTATES.mirror = true;
        this.setRotation(this.FUEL_BAR_3_ROTATES, 0.0F, 0.0F, 0.0F);
        this.FUEL_BAR_4_ROTATES = new ModelRenderer(this, 0, 54);
        this.FUEL_BAR_4_ROTATES.addBox(-4.0F, 0.0F, -1.0F, 2, 9, 2);
        this.FUEL_BAR_4_ROTATES.setRotationPoint(0.0F, 12.0F, 0.0F);
        this.FUEL_BAR_4_ROTATES.setTextureSize(128, 128);
        this.FUEL_BAR_4_ROTATES.mirror = true;
        this.setRotation(this.FUEL_BAR_4_ROTATES, 0.0F, 0.0F, 0.0F);
        this.CONVERTER = new ModelRenderer(this, 35, 56);
        this.CONVERTER.addBox(0.0F, 0.0F, 0.0F, 7, 10, 1);
        this.CONVERTER.setRotationPoint(-1.0F, 13.0F, 6.0F);
        this.CONVERTER.setTextureSize(128, 128);
        this.CONVERTER.mirror = true;
        this.setRotation(this.CONVERTER, 0.0F, 0.296706F, 0.0F);
        this.SUB_SHIELD_1 = new ModelRenderer(this, 53, 37);
        this.SUB_SHIELD_1.addBox(0.0F, 0.0F, 0.0F, 1, 4, 4);
        this.SUB_SHIELD_1.setRotationPoint(8.0F, 19.0F, -5.0F);
        this.SUB_SHIELD_1.setTextureSize(128, 128);
        this.SUB_SHIELD_1.mirror = true;
        this.setRotation(this.SUB_SHIELD_1, 0.0F, -2.094395F, 0.0F);
        this.SUB_SHIELD_2 = new ModelRenderer(this, 30, 37);
        this.SUB_SHIELD_2.addBox(0.0F, 0.0F, 0.0F, 1, 4, 10);
        this.SUB_SHIELD_2.setRotationPoint(7.0F, 19.0F, -5.0F);
        this.SUB_SHIELD_2.setTextureSize(128, 128);
        this.SUB_SHIELD_2.mirror = true;
        this.setRotation(this.SUB_SHIELD_2, 0.0F, 0.0F, 0.0F);
        this.Shape1 = new ModelRenderer(this, 10, 65);
        this.Shape1.addBox(0.0F, 0.0F, 0.0F, 5, 2, 5);
        this.Shape1.setRotationPoint(-7.0F, 22.0F, -7.0F);
        this.Shape1.setTextureSize(128, 128);
        this.Shape1.mirror = true;
        this.setRotation(this.Shape1, 0.1745329F, 0.0F, 0.0F);
    }

    public void render(float rotation, float f5) {
        this.BASE.render(f5);
        this.SHIELD_1.render(f5);
        this.SHIELD_2.render(f5);
        this.SHIELD_3.render(f5);
        this.SHIELD_4.render(f5);
        this.REACTOR_SUPPORT_ROD_ROTATES.rotateAngleY = rotation;
        this.REACTOR_SUPPORT_ROD_ROTATES.render(f5);
        this.SUPPORT_PLATE_1_ROTATES.rotateAngleY = rotation;
        this.SUPPORT_PLATE_1_ROTATES.render(f5);
        this.SUPPORT_PLATE_2_ROTATES.rotateAngleY = rotation;
        this.SUPPORT_PLATE_2_ROTATES.render(f5);
        this.FUEL_BAR_1_ROTATES.rotateAngleY = rotation;
        this.FUEL_BAR_1_ROTATES.render(f5);
        this.FUEL_BAR_2_ROTATES.rotateAngleY = rotation;
        this.FUEL_BAR_2_ROTATES.render(f5);
        this.FUEL_BAR_3_ROTATES.rotateAngleY = rotation;
        this.FUEL_BAR_3_ROTATES.render(f5);
        this.FUEL_BAR_4_ROTATES.rotateAngleY = rotation;
        this.FUEL_BAR_4_ROTATES.render(f5);
        this.CONVERTER.render(f5);
        this.SUB_SHIELD_1.render(f5);
        this.SUB_SHIELD_2.render(f5);
        this.Shape1.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
